use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

/// Convert git remote URL to HTTPS base URL for homepage/issues.
fn git_remote_to_https(url: &str) -> String {
    let url = url.trim();
    if url.starts_with("https://") || url.starts_with("http://") {
        return url
            .trim_end_matches('/')
            .trim_end_matches(".git")
            .to_string();
    }
    if url.starts_with("ssh://") {
        return url
            .replacen("ssh://", "https://", 1)
            .trim_end_matches('/')
            .trim_end_matches(".git")
            .to_string();
    }
    if let Some(after) = url.strip_prefix("git@") {
        let (host, path) = after
            .split_once(':')
            .or_else(|| after.split_once("/"))
            .unwrap_or((after, ""));
        let path = path.trim_end_matches(".git").trim_start_matches('/');
        if path.is_empty() {
            format!("https://{}", host)
        } else {
            format!("https://{}/{}", host, path)
        }
    } else {
        url.to_string()
    }
}

fn main() {
    tauri_build::build();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let generated_path = Path::new(&out_dir).join("git_urls.rs");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let package_json = Path::new(&manifest_dir).join("../package.json");

    let homepage_url = fs::read_to_string(&package_json)
        .ok()
        .and_then(|s| {
            let key = "\"repository\"";
            s.find(key).and_then(|start| {
                let after = &s[start + key.len()..];
                let colon = after.find(':')?;
                let after_colon = &after[colon + 1..];
                let open_quote = after_colon.find('"')? + 1;
                let value_start = &after_colon[open_quote..];
                let close = value_start.find('"')?;
                Some(value_start[..close].to_string())
            })
        })
        .filter(|s| !s.is_empty())
        .map(|s| s.trim_end_matches('/').trim_end_matches(".git").to_string())
        .or_else(|| {
            Command::new("git")
                .args(["config", "--get", "remote.origin.url"])
                .output()
                .ok()
                .and_then(|o| {
                    if o.status.success() {
                        String::from_utf8(o.stdout).ok()
                    } else {
                        None
                    }
                })
                .map(|s| git_remote_to_https(&s))
        })
        .unwrap_or_else(|| "https://github.com/otternews/media-metadata-cleaner".to_string());

    let issues_url = format!("{}/issues", homepage_url);

    let escape = |s: &str| s.replace('\\', "\\\\").replace('"', "\\\"");
    let content = format!(
        r#"// Generated by build.rs from git config
pub const HOMEPAGE_URL: &str = "{}";
pub const ISSUES_URL: &str = "{}";
"#,
        escape(&homepage_url),
        escape(&issues_url)
    );

    fs::write(&generated_path, content).expect("write generated git_urls.rs");
    println!("cargo:rerun-if-changed=../package.json");
    println!("cargo:rerun-if-changed=.git/config");
}
