use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

include!("src/url_utils.rs");

fn homepage_from_package_json(path: &Path) -> Option<String> {
    let content = fs::read_to_string(path).ok()?;
    let value: serde_json::Value = serde_json::from_str(&content).ok()?;
    let repo = value["repository"].as_str()?;
    let trimmed = repo.trim_end_matches('/').trim_end_matches(".git");
    if trimmed.is_empty() { None } else { Some(trimmed.to_string()) }
}

fn homepage_from_git_remote() -> Option<String> {
    let output = Command::new("git")
        .args(["config", "--get", "remote.origin.url"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout).ok().map(|s| git_remote_to_https(&s))
}

fn main() {
    tauri_build::build();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let generated_path = Path::new(&out_dir).join("git_urls.rs");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let package_json = Path::new(&manifest_dir).join("../package.json");

    let homepage_url = homepage_from_package_json(&package_json)
        .or_else(homepage_from_git_remote)
        .unwrap_or_else(|| "https://github.com/otternews/media-metadata-cleaner".to_string());

    let issues_url = format!("{}/issues", homepage_url);

    let escape = |s: &str| s.replace('\\', "\\\\").replace('"', "\\\"");
    let content = format!(
        "// Generated by build.rs\n\
         pub const HOMEPAGE_URL: &str = \"{}\";\n\
         pub const ISSUES_URL: &str = \"{}\";\n",
        escape(&homepage_url),
        escape(&issues_url),
    );

    fs::write(&generated_path, content).expect("write generated git_urls.rs");
    println!("cargo:rerun-if-changed=../package.json");
    println!("cargo:rerun-if-changed=.git/config");
}
